# Generated by Django 5.1.2 on 2025-02-11 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0030_remove_cursosocio_id_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(2000)], verbose_name='Año del Curso')),
                ('importe_matricula', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota Inscripció')),
                ('pago_inscripcion', models.BooleanField(verbose_name='Pagó Inscripcion')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='curso.curso')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Matricula de Socios',
                'constraints': [models.UniqueConstraint(fields=('id_socio', 'id_curso', 'anio'), name='unique_socio_curso')],
            },
        ),
    ]
