# Generated by Django 5.1.2 on 2025-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosocio',
            name='importe_matricula',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota Inscripción'),
        ),
    ]
