# Generated by Django 5.1.2 on 2025-02-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_cursosocio_importe_matricula'),
        ('socios', '0030_remove_cursosocio_id_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosocio',
            options={'verbose_name': 'Matricula de Socio', 'verbose_name_plural': 'Matricula de Socios'},
        ),
        migrations.AlterField(
            model_name='cursosocio',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='curso.curso', verbose_name='Materia que Cursa'),
        ),
        migrations.AlterField(
            model_name='cursosocio',
            name='id_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio', verbose_name='Nombre Socio'),
        ),
    ]
