# Generated by Django 3.2.15 on 2022-09-22 01:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0024_auto_20220921_2222'),
        ('personas', '0003_persona_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(default='', max_length=50)),
                ('contenido', ckeditor.fields.RichTextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Descriptores',
            },
        ),
        migrations.CreateModel(
            name='ActaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='actas.acta')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio', verbose_name='Nombre Socio')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios Participantes',
            },
        ),
        migrations.CreateModel(
            name='ActaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='actas.acta')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona', verbose_name='Nombre Persona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas Participantes',
            },
        ),
        migrations.CreateModel(
            name='ActaDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='actas.acta')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='actas.descriptor')),
            ],
            options={
                'verbose_name': 'Descriptor',
                'verbose_name_plural': 'Descriptores',
            },
        ),
        migrations.AddConstraint(
            model_name='actasocio',
            constraint=models.UniqueConstraint(fields=('id_acta', 'id_socio'), name='unique_acta_socio'),
        ),
        migrations.AddConstraint(
            model_name='actapersona',
            constraint=models.UniqueConstraint(fields=('id_acta', 'id_persona'), name='unique_acta_persona'),
        ),
        migrations.AddConstraint(
            model_name='actadescriptor',
            constraint=models.UniqueConstraint(fields=('acta', 'descriptor'), name='unique_acta_descriptor'),
        ),
    ]
