# Generated by Django 3.2.15 on 2022-09-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='actas.acta')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
            ],
            options={
                'verbose_name_plural': 'Socios en Acta',
            },
        ),
    ]
