# Generated by Django 3.2.15 on 2023-03-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actapersona',
            options={'verbose_name': 'Persona Participante', 'verbose_name_plural': 'Personas Participantes'},
        ),
        migrations.AlterModelOptions(
            name='actasocio',
            options={'verbose_name': 'Socio Participante', 'verbose_name_plural': 'Socios Participantes'},
        ),
        migrations.AlterModelOptions(
            name='descriptor',
            options={'verbose_name': 'Descriptor', 'verbose_name_plural': 'Descriptores'},
        ),
    ]
