# Generated by Django 3.2.15 on 2022-09-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_actapersona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actadescriptor',
            options={'verbose_name_plural': 'Descriptores'},
        ),
        migrations.AlterModelOptions(
            name='actapersona',
            options={'verbose_name_plural': 'Personas en Acta'},
        ),
    ]
