# Generated by Django 3.2.15 on 2022-09-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_lugartrabajo_options'),
        ('socios', '0029_delete_movimientocaja'),
        ('actas', '0003_auto_20220921_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actadescriptor',
            options={'verbose_name': 'Descriptor', 'verbose_name_plural': 'Descriptores'},
        ),
        migrations.AlterModelOptions(
            name='actapersona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas Participantes'},
        ),
        migrations.AlterModelOptions(
            name='actasocio',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios Participantes'},
        ),
        migrations.AlterField(
            model_name='actapersona',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona', verbose_name='Nombre Persona'),
        ),
        migrations.AlterField(
            model_name='actasocio',
            name='id_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio', verbose_name='Nombre Socio'),
        ),
        migrations.AddConstraint(
            model_name='actadescriptor',
            constraint=models.UniqueConstraint(fields=('acta', 'descriptor'), name='unique_acta_descriptor'),
        ),
        migrations.AddConstraint(
            model_name='actapersona',
            constraint=models.UniqueConstraint(fields=('id_acta', 'id_persona'), name='unique_acta_persona'),
        ),
        migrations.AddConstraint(
            model_name='actasocio',
            constraint=models.UniqueConstraint(fields=('id_acta', 'id_socio'), name='unique_acta_socio'),
        ),
    ]
