# Generated by Django 3.2.15 on 2022-08-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id_persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.persona'),
        ),
    ]
