# Generated by Django 3.2.15 on 2022-08-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20220812_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generada', models.DateField(auto_created=True)),
                ('estado', models.CharField(choices=[('P', 'PAGA'), ('N', 'NO PAGA')], default='N', max_length=1)),
                ('mes_anio', models.DateField(verbose_name='Mes-Año')),
                ('fecha_vencimiento', models.DateField()),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio')),
            ],
        ),
    ]
