# Generated by Django 3.2.15 on 2022-08-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_auto_20220817_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contenido', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='id_cuota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='socios.cuota'),
        ),
        migrations.CreateModel(
            name='ActaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.acta')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='ActaDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.acta')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.descriptor')),
            ],
        ),
    ]
