# Generated by Django 3.2.15 on 2022-08-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_auto_20220817_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='asunto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='acta',
            name='contenido',
            field=models.TextField(max_length=5000),
        ),
    ]
