# Generated by Django 3.2.15 on 2022-08-26 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_auto_20220817_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='metodo_pago',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='socios.metodopago'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='referencia',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
