# Generated by Django 3.2.15 on 2022-08-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_auto_20220826_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_socio',
            options={'verbose_name_plural': 'Categoría de Socios'},
        ),
        migrations.AlterModelOptions(
            name='descriptor',
            options={'verbose_name_plural': 'Descriptores'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name_plural': 'Método de Pago'},
        ),
        migrations.AlterModelOptions(
            name='pagocuota',
            options={'verbose_name_plural': 'Pago de Cuotas'},
        ),
    ]
