# Generated by Django 3.2.15 on 2022-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_socio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='importe',
            field=models.FloatField(default=0.0),
        ),
    ]
