# Generated by Django 3.2.15 on 2022-08-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0010_cuota_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='socios.metodopago'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='referencia',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
