# Generated by Django 3.2.15 on 2022-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0011_auto_20220829_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='referencia',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
