# Generated by Django 3.2.15 on 2022-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0012_alter_cuota_referencia'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('id_socio', 'mes_anio'), name='unique_socio_cuota'),
        ),
    ]
