# Generated by Django 3.2.15 on 2022-09-05 22:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0013_cuota_unique_socio_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='contenido',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
