# Generated by Django 3.2.15 on 2022-09-07 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0015_auto_20220906_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='departamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socios.departamento'),
        ),
    ]
