# Generated by Django 3.2.15 on 2022-09-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0014_alter_acta_contenido'),
        ('socios', '0016_alter_persona_departamento'),
    ]

    operations = [
    ]
