# Generated by Django 3.2.15 on 2022-09-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0017_auto_20220909_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formacion',
            options={'verbose_name_plural': 'Formaciones'},
        ),
        migrations.AlterModelOptions(
            name='lugartrabajo',
            options={'verbose_name_plural': 'Lugares de Trabajo'},
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_baja',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_reingreso',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de Reingreso'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id_persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socios.persona', verbose_name='Nombre'),
        ),
    ]
