# Generated by Django 3.2.15 on 2022-09-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('socios', '0017_auto_20220909_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoFromacion',
            new_name='TipoFormacion',
           
        ),
    ]
