# Generated by Django 3.2.15 on 2022-09-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0017_merge_20220907_2019'),
        ('socios', '0017_merge_20220907_2025'),
    ]

    operations = [
    ]
