# Generated by Django 3.2.15 on 2022-09-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0018_auto_20220914_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimiento', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SALIDA')], max_length=1)),
                ('tipo_caja', models.CharField(choices=[('S', 'Secretaria'), ('T', 'Tesoreria')], max_length=1)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
