# Generated by Django 3.2.15 on 2022-09-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('socios', '0020_movimientocaja_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='usuario',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
