# Generated by Django 3.2.15 on 2022-09-16 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0021_auto_20220915_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='grupo',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
