# Generated by Django 3.2.15 on 2022-09-21 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0022_auto_20220915_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_baja',
            field=models.DateField(blank=True, default=None, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_reingreso',
            field=models.DateField(blank=True, default=None, verbose_name='Fecha de Reingreso'),
        ),
    ]
