# Generated by Django 3.2.15 on 2022-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0023_auto_20220920_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='importe_cuota_jubilado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.CharField(choices=[('A', 'ALTA'), ('B', 'BAJA')], default='A', max_length=1),
        ),
    ]
