# Generated by Django 3.2.15 on 2022-09-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0024_auto_20220920_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_baja',
            field=models.DateField(blank=True, verbose_name='Fecha de Baja'),
        ),
    ]
