# Generated by Django 3.2.15 on 2022-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0024_auto_20220921_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
