# Generated by Django 3.2.15 on 2022-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0025_alter_socio_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
