# Generated by Django 3.2.15 on 2022-09-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0025_cuota_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
