# Generated by Django 3.2.15 on 2022-09-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0027_alter_socio_fecha_reingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actadescriptor',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='actadescriptor',
            name='descriptor',
        ),
        migrations.RemoveField(
            model_name='actasocio',
            name='id_acta',
        ),
        migrations.RemoveField(
            model_name='actasocio',
            name='id_socio',
        ),
        migrations.RemoveField(
            model_name='pagocuota',
            name='id_cuota',
        ),
        migrations.RemoveField(
            model_name='pagocuota',
            name='metodo_pago',
        ),
        migrations.DeleteModel(
            name='Acta',
        ),
        migrations.DeleteModel(
            name='ActaDescriptor',
        ),
        migrations.DeleteModel(
            name='ActaSocio',
        ),
        migrations.DeleteModel(
            name='Descriptor',
        ),
        migrations.DeleteModel(
            name='PagoCuota',
        ),
    ]
