# Generated by Django 3.2.15 on 2023-03-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0027_categoria_socio_voluntad'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_socio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='socio',
            name='importe_cuota_jubilado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe cuota voluntaria'),
        ),
    ]
