# Generated by Django 5.1.2 on 2025-02-10 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0027_categoria_socio_voluntad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='anio_cuota',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(2000)], verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='mes_cuota',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='importe_cuota_jubilado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe cuota voluntaria'),
        ),
    ]
