# Generated by Django 5.1.2 on 2025-02-10 23:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0028_cuota_anio_cuota_cuota_mes_cuota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('anio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(2000)], verbose_name='Año del Curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_inscripcion', models.BooleanField(verbose_name='Pagó Inscripcion')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.curso')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socios.socio')),
            ],
        ),
    ]
