# Generated by Django 3.2.15 on 2023-03-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0028_auto_20230329_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='numero_socio',
            field=models.IntegerField(default='1'),
        ),
    ]
