# Generated by Django 3.2.15 on 2022-09-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0028_auto_20220920_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
    ]
