# Generated by Django 5.1.2 on 2025-02-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0029_curso_cursosocio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosocio',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='cursosocio',
            name='id_socio',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='CursoSocio',
        ),
    ]
