# Generated by Django 3.2.15 on 2023-03-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0030_alter_socio_numero_socio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='numero_socio',
        ),
    ]
