# Generated by Django 3.2.15 on 2023-03-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0031_remove_socio_numero_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_socio',
            field=models.IntegerField(default=1, verbose_name='Numero Socio'),
        ),
    ]
