# Generated by Django 5.1.2 on 2025-02-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='tipo_caja',
        ),
    ]
