# Generated by Django 3.2.15 on 2022-09-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=45, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='LugarTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('perfil_cargo', models.ManyToManyField(to='personas.PerfilCargo')),
            ],
            options={
                'verbose_name_plural': 'Lugares de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_titulo', models.DateField(verbose_name='Fecha del Titulo')),
                ('institucion', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=100)),
                ('fecha_revalida', models.DateField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.persona')),
                ('tipo_formacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.tipoformacion')),
            ],
            options={
                'verbose_name_plural': 'Formaciones',
            },
        ),
    ]
