# Generated by Django 3.2.15 on 2022-09-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugartrabajo',
            options={'verbose_name': 'Lugar de Trabajo', 'verbose_name_plural': 'Lugares de Trabajo'},
        ),
    ]
