# Generated by Django 3.2.15 on 2022-09-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20220922_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tipoformacion',
            options={'verbose_name_plural': 'Tipo de Formaciones'},
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.genero'),
        ),
    ]
