# Generated by Django 3.2.15 on 2023-03-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20220923_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipoformacion',
            options={'verbose_name': 'Tipo de Formación', 'verbose_name_plural': 'Tipo de Formaciones'},
        ),
        migrations.AlterField(
            model_name='formacion',
            name='fecha_revalida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reválida'),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='fecha_titulo',
            field=models.DateField(verbose_name='Fecha del Título'),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='tipo_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.tipoformacion', verbose_name='Tipo de Formación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido_paterno',
            field=models.CharField(max_length=45, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.departamento', verbose_name='Lugar de Residencia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
