# Generated by Django 3.2.15 on 2023-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20230329_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
